# Generated by Django 6.0.3 on 2026-03-20 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('QUIZ', 'Quiz Assessment'), ('VIDEO', 'Video Assessment'), ('COMBINED', 'Combined Assessment')], max_length=20)),
                ('overall_diagnosis', models.CharField(max_length=50)),
                ('overall_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Assessment Histories',
                'db_table': 'assessments_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.FloatField(help_text='Time in video (seconds)')),
                ('emotion', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ANGRY', 'Angry'), ('FEAR', 'Fear'), ('SURPRISE', 'Surprise'), ('NEUTRAL', 'Neutral'), ('DISGUST', 'Disgust')], max_length=20)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('emotion_probabilities', models.JSONField(default=dict)),
                ('facial_landmarks', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'assessments_emotionframe',
                'ordering': ['video_analysis', 'frame_number'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quiz_type', models.CharField(choices=[('GENERAL', 'General Depression Screen'), ('ANXIETY', 'Anxiety Disorder Screen'), ('PTSD', 'PTSD Screen'), ('BIPOLAR', 'Bipolar Screen'), ('GAD', 'Generalized Anxiety Disorder'), ('PHQ9', 'PHQ-9 Depression Scale')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('total_questions', models.IntegerField()),
                ('model_used', models.CharField(default='naive_bayes', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'db_table': 'assessments_quiz',
                'ordering': ['quiz_type'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('score_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'assessments_quizoption',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('RADIO', 'Single Choice'), ('CHECKBOX', 'Multiple Choice'), ('SCALE', 'Likert Scale'), ('TEXT', 'Text Response')], max_length=20)),
                ('order', models.IntegerField()),
                ('max_score', models.IntegerField(default=10)),
                ('category', models.CharField(blank=True, help_text='e.g., mood, sleep, energy, etc.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessments_quizquestion',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('max_possible_score', models.IntegerField()),
                ('percentage_score', models.FloatField()),
                ('diagnosis', models.CharField(choices=[('NONE', 'No Depression Detected'), ('MILD', 'Mild Depression'), ('MODERATE', 'Moderate Depression'), ('SEVERE', 'Severe Depression'), ('ANXIETY', 'Anxiety Disorder'), ('PTSD', 'PTSD'), ('BIPOLAR', 'Bipolar Disorder')], max_length=50)),
                ('confidence', models.FloatField(help_text='Model confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('category_scores', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField()),
                ('device_type', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile')], max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessments_quizresult',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, null=True)),
                ('score_received', models.IntegerField()),
            ],
            options={
                'db_table': 'assessments_userquizresponse',
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/%Y/%m/%d/')),
                ('video_duration', models.IntegerField(help_text='Duration in seconds')),
                ('overall_emotion', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ANGRY', 'Angry'), ('FEAR', 'Fear'), ('SURPRISE', 'Surprise'), ('NEUTRAL', 'Neutral'), ('DISGUST', 'Disgust')], max_length=20)),
                ('emotion_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('emotion_timeline', models.JSONField(default=dict, help_text='Dictionary with timestamp and emotion for each frame')),
                ('depression_score', models.IntegerField(help_text='Calculated depression risk score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('depression_classification', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=50)),
                ('face_count', models.IntegerField(default=1)),
                ('frames_detected', models.IntegerField()),
                ('total_frames', models.IntegerField()),
                ('detection_confidence', models.FloatField(default=0.0)),
                ('eye_contact_percentage', models.FloatField(default=0.0)),
                ('smile_count', models.IntegerField(default=0)),
                ('blink_rate', models.FloatField(default=0.0)),
                ('speaking_rate', models.FloatField(default=0.0)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessments_videoanalysis',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
