# Generated by Django 6.0.3 on 2026-03-20 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz'),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.quizquestion'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.quiz'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenthistory',
            name='quiz_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.quizresult'),
        ),
        migrations.AddField(
            model_name='userquizresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.quizquestion'),
        ),
        migrations.AddField(
            model_name='userquizresponse',
            name='quiz_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.quizresult'),
        ),
        migrations.AddField(
            model_name='userquizresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.quizoption'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emotionframe',
            name='video_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='assessments.videoanalysis'),
        ),
        migrations.AddField(
            model_name='assessmenthistory',
            name='video_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.videoanalysis'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['user', '-completed_at'], name='assessments_user_id_6e1b02_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['quiz', '-completed_at'], name='assessments_quiz_id_e0fc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysis',
            index=models.Index(fields=['user', '-uploaded_at'], name='assessments_user_id_1ced2f_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysis',
            index=models.Index(fields=['depression_classification'], name='assessments_depress_5f5ddc_idx'),
        ),
    ]
